#!/bin/bash
#  extracted from https://github.com/awslabs/aws-lambda-cpp/blob/master/packaging/packager
#  Copyright 2018-present Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#   http://aws.amazon.com/apache2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.

set -euo pipefail

print_help() {
  echo -e "Usage: packager <binary name>\n"
}

if [ $# -lt 1 ]; then
  echo -e "Error: missing arguments\n"
  print_help
  exit 1
fi

PKG_BIN_PATH=$1

if [ ! -f "$PKG_BIN_PATH" ]; then
  echo "$PKG_BIN_PATH" - No such file.
  exit 1
fi

if ! type zip >/dev/null 2>&1; then
  echo "zip utility is not found. Please install it and re-run this script"
  exit 1
fi

PKG_BIN_FILENAME=$(basename "$PKG_BIN_PATH")
PKG_DIR="tmp_$PKG_BIN_FILENAME"

mkdir -p "$PKG_DIR/bin"

bootstrap_script=$(
cat <<EOF
#!/bin/bash
set -euo pipefail
export AWS_EXECUTION_ENV=lambda-zig
exec \$LAMBDA_TASK_ROOT/bin/$PKG_BIN_FILENAME \${_HANDLER}
EOF
)

cp "$PKG_BIN_PATH" "$PKG_DIR/bin"

echo -e "$bootstrap_script" >"$PKG_DIR/bootstrap"

chmod +x "$PKG_DIR/bootstrap"

# some shenanigans to create the right layout in the zip file without extraneous directories
pushd "$PKG_DIR" >/dev/null
zip -q --symlinks --recurse-paths "$PKG_BIN_FILENAME".zip -- *
ORIGIN_DIR=$(dirs -l +1)
mv "$PKG_BIN_FILENAME".zip "$ORIGIN_DIR"
popd >/dev/null
rm -r "$PKG_DIR"
echo Created "$ORIGIN_DIR/$PKG_BIN_FILENAME".zip
