name: Validate Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update Dependencies
      run: sudo apt-get update -y

    - name: Install Dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Run tests
      run: AWS_LAMBDA_RUNTIME_API="" zig build test
      
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Check Formatting
      run: ./ci/codebuild/format-check.sh
